name: My First Workflow
on: 
  push:
    branches: main
  workflow_dispatch: 
    inputs:
      logLevel:
        description: "Log Level"
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
  repository_dispatch:
    types:
      - hello
        

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - name: Checkout
        uses: actions/checkout@v6
      - name: List Files in the Repository
        run: |
          echo "Log level: ${{ inputs.logLevel }}"
          echo "This repository ${{ github.repository }} contains the following files:"
          tree
      - name: run something in python
        shell: python
        run: |
          print("Hello World")
      - name: throw warning
        run: |
          echo "::warning file:README.md,line=1,col=0,endColumn=10::Testing this out"
          echo "::debug::Debugging Message"
          echo "::error::Error Occurred Here!"
          echo "Here is a list
          * item 1
          * item 3
          * item 3" > $GITHUB_STEP_SUMMARY
      - name: secret test
        run: |
          echo "${{ secrets.MY_SECRET }}"
          echo "abc123"
